cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

stages:
  - build
  - test
  - Docker

Front_build:
  stage: build
  before_script:
    - npm install
  script:
    - set CI=false
    - npm run build


Front_Cypress_test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test
  before_script:
    - npm ci
    - npm start &
  script:
    - npx cypress run --browser firefox
  when: manual

Front_npm_test:
  stage: test
  before_script:
    - npm install
  script:
    - set CI=false
    - npm test
  

Docker_building:
  stage: Docker

  variables:
    DOCKER_IMAGE_NAME: $DOCKER_USERNAME"/front-end-semester-3-2023-fontys"
    DOCKER_REGISTRY: "docker.io"

  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"

  script:
    - docker build -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
    
  only:
    - main

