cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy
  - e2e test

Front_build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build

Front_test:
  stage: test
  before_script:
    - npm install
  script:
    - npm test

Front_deploy:
  stage: deploy
  script:
    - echo "deploy script here"
  only:
    - main

e2e_test:
  stage: e2e test
  script:
    - echo "deploy Do end to end test here"
  only:
    - main
  when: manual

