cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

stages:
  - build
  - test
  - deploy

Front_build:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build


Front_Cypress_test:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test
  before_script:
    - npm ci
    - npm start &
  script:
    - npx cypress run --browser firefox
  when: manual

Front_npm_test:
  stage: test
  before_script:
    - npm install
  script:
    - npm test
  

Front_deploy:
  stage: deploy
  script:
    - echo "deploy script here"
  only:
    - main

